import React from 'react';

const MonthlyReport = React.forwardRef(({ inspections, month, year }, ref) => {
  const totalInspections = inspections.length;
  const avgScore = totalInspections > 0 ? Math.round(inspections.reduce((acc, i) => acc + (i.score_pct || 0), 0) / totalInspections) : 0;
  const criticalAlerts = inspections.filter(i => i.alert_level === 'critical').length;

  return (
    <div ref={ref} style={{ padding: '40px', fontFamily: 'Arial, sans-serif', color: '#1F2937', width: '800px' }}>
      <div style={{ borderBottom: '4px solid #2F3E46', paddingBottom: '20px', marginBottom: '30px' }}>
        <h1 style={{ margin: 0, fontSize: '32px', fontWeight: 800, color: '#2F3E46' }}>NEMCHEM Moçambique</h1>
        <p style={{ margin: '4px 0 0 0', fontSize: '14px', textTransform: 'uppercase', letterSpacing: '2px', color: '#666' }}>Monthly Operations Report</p>
      </div>

      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '30px' }}>
        <h2 style={{ margin: 0, fontSize: '24px', color: '#1E2A3A' }}>{month} {year}</h2>
        <div style={{ textAlign: 'right' }}>
          <div style={{ fontSize: '36px', fontWeight: 800, color: avgScore >= 75 ? '#0F6E56' : '#A32D2D' }}>{avgScore}%</div>
          <div style={{ fontSize: '12px', color: '#888' }}>Average Score</div>
        </div>
      </div>

      <div style={{ display: 'flex', gap: '20px', marginBottom: '30px' }}>
        <div style={{ flex: 1, background: '#F9FAFB', padding: '16px', borderRadius: '8px', border: '1px solid #E5E7EB' }}>
          <div style={{ fontSize: '32px', fontWeight: 800, color: '#1E2A3A' }}>{totalInspections}</div>
          <div style={{ fontSize: '12px', color: '#666' }}>Total Inspections</div>
        </div>
        <div style={{ flex: 1, background: '#FEE2E2', padding: '16px', borderRadius: '8px', border: '1px solid #FECACA' }}>
          <div style={{ fontSize: '32px', fontWeight: 800, color: '#991B1B' }}>{criticalAlerts}</div>
          <div style={{ fontSize: '12px', color: '#991B1B' }}>Critical Alerts</div>
        </div>
      </div>

      <h3 style={{ fontSize: '18px', color: '#1E2A3A', borderBottom: '2px solid #eee', paddingBottom: '8px', marginBottom: '16px' }}>Inspection Details</h3>
      
      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '12px' }}>
        <thead>
          <tr style={{ background: '#2F3E46', color: '#fff' }}>
            <th style={{ padding: '8px', textAlign: 'left' }}>Client</th>
            <th style={{ padding: '8px', textAlign: 'left' }}>Inspector</th>
            <th style={{ padding: '8px', textAlign: 'center' }}>Score</th>
            <th style={{ padding: '8px', textAlign: 'left' }}>Status</th>
          </tr>
        </thead>
        <tbody>
          {inspections.map(insp => (
            <tr key={insp.id} style={{ borderBottom: '1px solid #eee' }}>
              <td style={{ padding: '8px', fontWeight: 500 }}>{insp.location_name}</td>
              <td style={{ padding: '8px' }}>{insp.inspector_name || 'N/A'}</td>
              <td style={{ padding: '8px', textAlign: 'center', fontWeight: 700, color: insp.score_pct >= 75 ? '#0F6E56' : insp.score_pct >= 50 ? '#BA7517' : '#A32D2D' }}>{insp.score_pct || 0}%</td>
              <td style={{ padding: '8px' }}>{insp.status}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div style={{ marginTop: '40px', textAlign: 'center', fontSize: '10px', color: '#999' }}>
        Generated by FIMS | NEMCHEM Moçambique
      </div>
    </div>
  );
});

export default MonthlyReport;
