import React from 'react';

const ReportFrame = ({ children, inspectionType = "Quality Inspection Report" }) => {
  return (
    <div style={{ 
      width: '210mm', 
      minHeight: '297mm', 
      backgroundColor: '#fff', 
      padding: '40px 40px 60px 40px', 
      fontFamily: 'Helvetica, Arial, sans-serif', 
      color: '#1F2937', 
      fontSize: '11pt', 
      lineHeight: '1.4', 
      position: 'relative',
      boxSizing: 'border-box'
    }}>
      
      {/* 1. UNIVERSAL HEADER */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', borderBottom: '2px solid #1E2A3A', paddingBottom: '15px', marginBottom: '30px' }}>
        <div>
          <img src="/logo.png" alt="NemChem Logo" style={{ height: '50px', marginBottom: '4px' }} />
          <div style={{ fontSize: '9pt', fontWeight: 700, color: '#1E2A3A', textTransform: 'uppercase', letterSpacing: '1px' }}>The Professional Choice</div>
        </div>
        <div style={{ textAlign: 'right', fontSize: '9pt', color: '#4B5563' }}>
          <div style={{ fontWeight: 700, color: '#1E2A3A', fontSize: '11pt' }}>{inspectionType}</div>
          <div>Powered by FIMS</div>
        </div>
      </div>

      {/* 2. CONTENT AREA (Children passed in here) */}
      <div>
        {children}
      </div>

      {/* 3. UNIVERSAL FOOTER */}
      <div style={{ position: 'absolute', bottom: '20px', left: '40px', right: '40px', borderTop: '1px solid #E5E7EB', paddingTop: '10px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div style={{ fontSize: '8pt', color: '#9CA3AF' }}>
          <strong style={{ color: '#4B5563' }}>NemChem Moçambique</strong> | Tel: +258 84 000 0000 | info@nemchem.co.mz
        </div>
        <div style={{ fontSize: '8pt', color: '#9CA3AF' }}>
          Generated by FIMS
        </div>
      </div>
    </div>
  );
};

export default ReportFrame;
